  name: Build and deploy workflow
  on:
    push:
      branches:
        - '*'
    workflow_dispatch: {}
  jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - run: echo 'All good'

    Deploy:
      strategy:
        matrix:
          environment: ['dev', 'staging', 'prod']
      concurrency: dev
      environment: ${{ matrix.environment }}
      runs-on: ubuntu-latest

      steps:
        - name: Dump job context
          env:
            GITHUB_CONTEXT: ${{ toJson(job) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Dump env context
          env:
            GITHUB_CONTEXT: ${{ toJson(env) }}
          run: echo "$GITHUB_CONTEXT"
#    Deploy-Staging:
#      strategy:
#        matrix:
#          environments: ['dev', 'staging', 'prod']
#      concurrency: staging
#      runs-on: ubuntu-latest
#
#      steps:
#        - run: echo done
